name: edc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - accelerate==0.29.1
      - aiohttp==3.9.3
      - aiosignal==1.2.0
      - annotated-types==0.6.0
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.7.0
      - bottleneck==1.3.7
      - brotli==1.0.9
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==2.0.4
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datasets==2.12.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.6
      - distro==1.9.0
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - flask==3.0.3
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gmpy2==2.1.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.20.3
      - idna==3.4
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - intel-openmp==2024.1.0
      - ipykernel==6.29.3
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.0
      - json5==0.9.25
      - jsonpickle==3.0.4
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.1
      - jupyter-console==6.6.3
      - jupyter-contrib-core==0.4.2
      - jupyter-contrib-nbextensions==0.7.0
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-highlight-selected-word==0.2.0
      - jupyter-lsp==2.2.5
      - jupyter-nbextensions-configurator==0.6.3
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.26.0
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.5
      - lxml==5.2.1
      - markupsafe==2.1.3
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mkl==2024.1.0
      - mkl-fft==1.3.8
      - mkl-random==1.2.4
      - mkl-service==2.4.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - nervaluate==0.1.8
      - nest-asyncio==1.6.0
      - networkx==3.1
      - nltk==3.8.1
      - notebook==7.1.2
      - notebook-shim==0.2.4
      - numexpr==2.8.7
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.16.2
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.10.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.2.0
      - plotly==5.20.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.42
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==14.0.2
      - pycparser==2.22
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyvis==0.3.2
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.34.0
      - regex==2023.10.3
      - requests==2.31.0
      - responses==0.13.3
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - safetensors==0.4.2
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.2
      - sympy==1.12
      - tbb==2021.12.0
      - tenacity==8.2.3
      - terminado==0.18.1
      - threadpoolctl==3.4.0
      - tinycss2==1.2.1
      - tokenizers==0.15.1
      - tomli==2.0.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tornado==6.4
      - tqdm==4.65.0
      - traitlets==5.14.2
      - transformers==4.39.3
      - triton==2.2.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.9.0
      - tzdata==2023.3
      - unidecode==1.3.8
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.2
      - widgetsnbextension==4.0.8
      - xxhash==2.0.2
      - yarl==1.9.3
      - zipp==3.17.0
prefix: /home/users/bowenzhang/miniconda3/envs/edc
